use crate::language::Token;

/// Syntax kinds for the VB6 CST.
///
/// This enum represents all possible node and token types in the CST.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize)]
#[repr(u16)]
pub enum SyntaxKind {
    // Root node
    Root = 0,

    // Statement nodes
    ModuleStatement,
    ClassStatement,
    SubStatement,
    FunctionStatement,
    PropertyStatement,
    DeclareStatement,
    EventStatement,
    ImplementsStatement,
    DefTypeStatement,
    DimStatement,
    ReDimStatement,
    EraseStatement,
    ConstStatement,
    TypeStatement,
    EnumStatement,
    IfStatement,
    ElseIfClause,
    ElseClause,
    ForStatement,
    ForEachStatement,
    WhileStatement,
    DoStatement,
    SelectCaseStatement,
    CaseClause,
    CaseElseClause,
    WithStatement,
    CallStatement,
    RaiseEventStatement,
    SetStatement,
    LetStatement,
    AssignmentStatement,
    GotoStatement,
    GoSubStatement,
    ReturnStatement,
    ResumeStatement,
    ExitStatement,
    OnErrorStatement,
    OnGoToStatement,
    OnGoSubStatement,
    AppActivateStatement,
    BeepStatement,
    ChDirStatement,
    ChDriveStatement,
    CloseStatement,
    DateStatement,
    DeleteSettingStatement,
    ResetStatement,
    SavePictureStatement,
    SaveSettingStatement,
    SeekStatement,
    SendKeysStatement,
    SetAttrStatement,
    StopStatement,
    TimeStatement,
    RandomizeStatement,
    ErrorStatement,
    FileCopyStatement,
    GetStatement,
    PutStatement,
    InputStatement,
    LineInputStatement,
    KillStatement,
    LoadStatement,
    UnloadStatement,
    LockStatement,
    UnlockStatement,
    LSetStatement,
    RSetStatement,
    MidStatement,
    MidBStatement,
    MkDirStatement,
    RmDirStatement,
    NameStatement,
    OpenStatement,
    PrintStatement,
    WidthStatement,
    WriteStatement,
    LabelStatement,
    AttributeStatement,
    OptionStatement,
    ObjectStatement,

    // Class/Form Header nodes
    VersionStatement,
    PropertiesBlock,
    PropertiesType,
    PropertiesName,
    Property,
    PropertyKey,
    PropertyValue,
    PropertyGroup,
    PropertyGroupName,

    // Expression nodes
    BinaryExpression,
    UnaryExpression,
    LiteralExpression,
    IdentifierExpression,
    MemberAccessExpression,
    CallExpression,
    ParenthesizedExpression,
    NumericLiteralExpression,
    StringLiteralExpression,
    BooleanLiteralExpression,
    AddressOfExpression,
    TypeOfExpression,
    NewExpression,

    // Conditional nodes
    BinaryConditional,
    UnaryConditional,

    // Other structural nodes
    ArgumentList,
    ParameterList,
    Parameter,
    Argument,
    CodeBlock,

    // Token kinds - map from VB6Token
    // We start these at a higher offset to avoid conflicts
    Whitespace = 1000,
    Newline,
    EndOfLineComment,
    RemComment,

    // Keywords
    ClassKeyword,
    ReDimKeyword,
    PreserveKeyword,
    DimKeyword,
    DeclareKeyword,
    AliasKeyword,
    AttributeKeyword,
    BeginKeyword,
    LibKeyword,
    WithKeyword,
    WithEventsKeyword,
    BaseKeyword,
    CompareKeyword,
    OptionKeyword,
    ExplicitKeyword,
    PrivateKeyword,
    PublicKeyword,
    ConstKeyword,
    AsKeyword,
    ByValKeyword,
    ByRefKeyword,
    OptionalKeyword,
    FunctionKeyword,
    StaticKeyword,
    SubKeyword,
    EndKeyword,
    TrueKeyword,
    FalseKeyword,
    EnumKeyword,
    TypeKeyword,
    BooleanKeyword,
    DoubleKeyword,
    CurrencyKeyword,
    DecimalKeyword,
    DateKeyword,
    ObjectKeyword,
    VariantKeyword,
    ByteKeyword,
    LongKeyword,
    SingleKeyword,
    StringKeyword,
    IntegerKeyword,
    IfKeyword,
    ElseKeyword,
    ElseIfKeyword,
    AndKeyword,
    OrKeyword,
    XorKeyword,
    ModKeyword,
    EqvKeyword,
    AddressOfKeyword,
    ImpKeyword,
    IsKeyword,
    LikeKeyword,
    NotKeyword,
    ThenKeyword,
    GotoKeyword,
    GoSubKeyword,
    ReturnKeyword,
    ExitKeyword,
    ForKeyword,
    EachKeyword,
    InKeyword,
    ToKeyword,
    LockKeyword,
    UnlockKeyword,
    StepKeyword,
    StopKeyword,
    WhileKeyword,
    WendKeyword,
    WidthKeyword,
    WriteKeyword,
    TimeKeyword,
    SetAttrKeyword,
    SetKeyword,
    SendKeysKeyword,
    SelectKeyword,
    CaseKeyword,
    SeekKeyword,
    SaveSettingKeyword,
    SavePictureKeyword,
    RSetKeyword,
    RmDirKeyword,
    ResumeKeyword,
    ResetKeyword,
    RandomizeKeyword,
    RaiseEventKeyword,
    PutKeyword,
    PropertyKeyword,
    PrintKeyword,
    OpenKeyword,
    OnKeyword,
    OffKeyword,
    NameKeyword,
    MkDirKeyword,
    MidKeyword,
    MidBKeyword,
    LSetKeyword,
    LoadKeyword,
    UnloadKeyword,
    LineKeyword,
    InputKeyword,
    LetKeyword,
    KillKeyword,
    ImplementsKeyword,
    GetKeyword,
    FileCopyKeyword,
    EventKeyword,
    ErrorKeyword,
    EraseKeyword,
    DoKeyword,
    UntilKeyword,
    DeleteSettingKeyword,
    DefBoolKeyword,
    DefByteKeyword,
    DefIntKeyword,
    DefLngKeyword,
    DefCurKeyword,
    DefSngKeyword,
    DefDblKeyword,
    DefDecKeyword,
    DefDateKeyword,
    DefStrKeyword,
    DefObjKeyword,
    DefVarKeyword,
    CloseKeyword,
    ChDriveKeyword,
    ChDirKeyword,
    CallKeyword,
    BeepKeyword,
    AppActivateKeyword,
    FriendKeyword,
    BinaryKeyword,
    RandomKeyword,
    ReadKeyword,
    OutputKeyword,
    AppendKeyword,
    AccessKeyword,
    TextKeyword,
    DatabaseKeyword,
    EmptyKeyword,
    ModuleKeyword,
    NextKeyword,
    NewKeyword,
    LenKeyword,
    MeKeyword,
    NullKeyword,
    ParamArrayKeyword,
    VersionKeyword,
    LoopKeyword,
    NothingKeyword,
    AnyKeyword,

    // Literals and identifiers
    Identifier,
    StringLiteral,
    IntegerLiteral,
    LongLiteral,
    SingleLiteral,
    DoubleLiteral,
    DecimalLiteral,
    CurrencyLiteral,
    DateLiteral,

    // Operators and punctuation
    DollarSign,
    Underscore,
    Ampersand,
    Percent,
    Octothorpe,
    LeftParenthesis,
    RightParenthesis,
    LeftSquareBracket,
    RightSquareBracket,
    Comma,
    Semicolon,
    AtSign,
    ExclamationMark,
    EqualityOperator,
    InequalityOperator,
    LessThanOrEqualOperator,
    GreaterThanOrEqualOperator,
    LessThanOperator,
    GreaterThanOperator,
    MultiplicationOperator,
    SubtractionOperator,
    AdditionOperator,
    DivisionOperator,
    BackwardSlashOperator,
    PeriodOperator,
    ColonOperator,
    ExponentiationOperator,

    // Error recovery
    Error,
    Unknown,
}

impl From<Token> for SyntaxKind {
    fn from(token: Token) -> Self {
        match token {
            Token::Whitespace => SyntaxKind::Whitespace,
            Token::Newline => SyntaxKind::Newline,
            Token::EndOfLineComment => SyntaxKind::EndOfLineComment,
            Token::RemComment => SyntaxKind::RemComment,
            Token::ClassKeyword => SyntaxKind::ClassKeyword,
            Token::ReDimKeyword => SyntaxKind::ReDimKeyword,
            Token::PreserveKeyword => SyntaxKind::PreserveKeyword,
            Token::DimKeyword => SyntaxKind::DimKeyword,
            Token::DeclareKeyword => SyntaxKind::DeclareKeyword,
            Token::AliasKeyword => SyntaxKind::AliasKeyword,
            Token::AttributeKeyword => SyntaxKind::AttributeKeyword,
            Token::BeginKeyword => SyntaxKind::BeginKeyword,
            Token::LibKeyword => SyntaxKind::LibKeyword,
            Token::WithKeyword => SyntaxKind::WithKeyword,
            Token::WithEventsKeyword => SyntaxKind::WithEventsKeyword,
            Token::BaseKeyword => SyntaxKind::BaseKeyword,
            Token::CompareKeyword => SyntaxKind::CompareKeyword,
            Token::OptionKeyword => SyntaxKind::OptionKeyword,
            Token::ExplicitKeyword => SyntaxKind::ExplicitKeyword,
            Token::PrivateKeyword => SyntaxKind::PrivateKeyword,
            Token::PublicKeyword => SyntaxKind::PublicKeyword,
            Token::ConstKeyword => SyntaxKind::ConstKeyword,
            Token::AsKeyword => SyntaxKind::AsKeyword,
            Token::ByValKeyword => SyntaxKind::ByValKeyword,
            Token::ByRefKeyword => SyntaxKind::ByRefKeyword,
            Token::OptionalKeyword => SyntaxKind::OptionalKeyword,
            Token::FunctionKeyword => SyntaxKind::FunctionKeyword,
            Token::StaticKeyword => SyntaxKind::StaticKeyword,
            Token::SubKeyword => SyntaxKind::SubKeyword,
            Token::EndKeyword => SyntaxKind::EndKeyword,
            Token::TrueKeyword => SyntaxKind::TrueKeyword,
            Token::FalseKeyword => SyntaxKind::FalseKeyword,
            Token::EnumKeyword => SyntaxKind::EnumKeyword,
            Token::TypeKeyword => SyntaxKind::TypeKeyword,
            Token::BooleanKeyword => SyntaxKind::BooleanKeyword,
            Token::DoubleKeyword => SyntaxKind::DoubleKeyword,
            Token::CurrencyKeyword => SyntaxKind::CurrencyKeyword,
            Token::DecimalKeyword => SyntaxKind::DecimalKeyword,
            Token::DateKeyword => SyntaxKind::DateKeyword,
            Token::ObjectKeyword => SyntaxKind::ObjectKeyword,
            Token::VariantKeyword => SyntaxKind::VariantKeyword,
            Token::ByteKeyword => SyntaxKind::ByteKeyword,
            Token::LongKeyword => SyntaxKind::LongKeyword,
            Token::SingleKeyword => SyntaxKind::SingleKeyword,
            Token::StringKeyword => SyntaxKind::StringKeyword,
            Token::IntegerKeyword => SyntaxKind::IntegerKeyword,
            Token::StringLiteral => SyntaxKind::StringLiteral,
            Token::IntegerLiteral => SyntaxKind::IntegerLiteral,
            Token::LongLiteral => SyntaxKind::LongLiteral,
            Token::SingleLiteral => SyntaxKind::SingleLiteral,
            Token::DoubleLiteral => SyntaxKind::DoubleLiteral,
            Token::DecimalLiteral => SyntaxKind::DecimalLiteral,
            Token::DateLiteral => SyntaxKind::DateLiteral,
            Token::IfKeyword => SyntaxKind::IfKeyword,
            Token::ElseKeyword => SyntaxKind::ElseKeyword,
            Token::ElseIfKeyword => SyntaxKind::ElseIfKeyword,
            Token::AndKeyword => SyntaxKind::AndKeyword,
            Token::OrKeyword => SyntaxKind::OrKeyword,
            Token::XorKeyword => SyntaxKind::XorKeyword,
            Token::ModKeyword => SyntaxKind::ModKeyword,
            Token::EqvKeyword => SyntaxKind::EqvKeyword,
            Token::AddressOfKeyword => SyntaxKind::AddressOfKeyword,
            Token::ImpKeyword => SyntaxKind::ImpKeyword,
            Token::IsKeyword => SyntaxKind::IsKeyword,
            Token::LikeKeyword => SyntaxKind::LikeKeyword,
            Token::NotKeyword => SyntaxKind::NotKeyword,
            Token::ThenKeyword => SyntaxKind::ThenKeyword,
            Token::GotoKeyword => SyntaxKind::GotoKeyword,
            Token::GoSubKeyword => SyntaxKind::GoSubKeyword,
            Token::ReturnKeyword => SyntaxKind::ReturnKeyword,
            Token::ExitKeyword => SyntaxKind::ExitKeyword,
            Token::ForKeyword => SyntaxKind::ForKeyword,
            Token::EachKeyword => SyntaxKind::EachKeyword,
            Token::InKeyword => SyntaxKind::InKeyword,
            Token::ToKeyword => SyntaxKind::ToKeyword,
            Token::LockKeyword => SyntaxKind::LockKeyword,
            Token::UnlockKeyword => SyntaxKind::UnlockKeyword,
            Token::StepKeyword => SyntaxKind::StepKeyword,
            Token::StopKeyword => SyntaxKind::StopKeyword,
            Token::WhileKeyword => SyntaxKind::WhileKeyword,
            Token::WendKeyword => SyntaxKind::WendKeyword,
            Token::WidthKeyword => SyntaxKind::WidthKeyword,
            Token::WriteKeyword => SyntaxKind::WriteKeyword,
            Token::TimeKeyword => SyntaxKind::TimeKeyword,
            Token::SetAttrKeyword => SyntaxKind::SetAttrKeyword,
            Token::SetKeyword => SyntaxKind::SetKeyword,
            Token::SendKeysKeyword => SyntaxKind::SendKeysKeyword,
            Token::SelectKeyword => SyntaxKind::SelectKeyword,
            Token::CaseKeyword => SyntaxKind::CaseKeyword,
            Token::SeekKeyword => SyntaxKind::SeekKeyword,
            Token::SaveSettingKeyword => SyntaxKind::SaveSettingKeyword,
            Token::SavePictureKeyword => SyntaxKind::SavePictureKeyword,
            Token::RSetKeyword => SyntaxKind::RSetKeyword,
            Token::RmDirKeyword => SyntaxKind::RmDirKeyword,
            Token::ResumeKeyword => SyntaxKind::ResumeKeyword,
            Token::ResetKeyword => SyntaxKind::ResetKeyword,
            Token::RandomizeKeyword => SyntaxKind::RandomizeKeyword,
            Token::RaiseEventKeyword => SyntaxKind::RaiseEventKeyword,
            Token::PutKeyword => SyntaxKind::PutKeyword,
            Token::PropertyKeyword => SyntaxKind::PropertyKeyword,
            Token::PrintKeyword => SyntaxKind::PrintKeyword,
            Token::OpenKeyword => SyntaxKind::OpenKeyword,
            Token::OnKeyword => SyntaxKind::OnKeyword,
            Token::OffKeyword => SyntaxKind::OffKeyword,
            Token::NameKeyword => SyntaxKind::NameKeyword,
            Token::MkDirKeyword => SyntaxKind::MkDirKeyword,
            Token::MidBKeyword => SyntaxKind::MidBKeyword,
            Token::MidKeyword => SyntaxKind::MidKeyword,
            Token::LSetKeyword => SyntaxKind::LSetKeyword,
            Token::LoadKeyword => SyntaxKind::LoadKeyword,
            Token::UnloadKeyword => SyntaxKind::UnloadKeyword,
            Token::LineKeyword => SyntaxKind::LineKeyword,
            Token::InputKeyword => SyntaxKind::InputKeyword,
            Token::LetKeyword => SyntaxKind::LetKeyword,
            Token::KillKeyword => SyntaxKind::KillKeyword,
            Token::ImplementsKeyword => SyntaxKind::ImplementsKeyword,
            Token::GetKeyword => SyntaxKind::GetKeyword,
            Token::FileCopyKeyword => SyntaxKind::FileCopyKeyword,
            Token::EventKeyword => SyntaxKind::EventKeyword,
            Token::ErrorKeyword => SyntaxKind::ErrorKeyword,
            Token::EraseKeyword => SyntaxKind::EraseKeyword,
            Token::DoKeyword => SyntaxKind::DoKeyword,
            Token::UntilKeyword => SyntaxKind::UntilKeyword,
            Token::LoopKeyword => SyntaxKind::LoopKeyword,
            Token::DeleteSettingKeyword => SyntaxKind::DeleteSettingKeyword,
            Token::DefBoolKeyword => SyntaxKind::DefBoolKeyword,
            Token::DefByteKeyword => SyntaxKind::DefByteKeyword,
            Token::DefIntKeyword => SyntaxKind::DefIntKeyword,
            Token::DefLngKeyword => SyntaxKind::DefLngKeyword,
            Token::DefCurKeyword => SyntaxKind::DefCurKeyword,
            Token::DefSngKeyword => SyntaxKind::DefSngKeyword,
            Token::DefDblKeyword => SyntaxKind::DefDblKeyword,
            Token::DefDecKeyword => SyntaxKind::DefDecKeyword,
            Token::DefDateKeyword => SyntaxKind::DefDateKeyword,
            Token::DefStrKeyword => SyntaxKind::DefStrKeyword,
            Token::DefObjKeyword => SyntaxKind::DefObjKeyword,
            Token::DefVarKeyword => SyntaxKind::DefVarKeyword,
            Token::CloseKeyword => SyntaxKind::CloseKeyword,
            Token::ChDriveKeyword => SyntaxKind::ChDriveKeyword,
            Token::ChDirKeyword => SyntaxKind::ChDirKeyword,
            Token::CallKeyword => SyntaxKind::CallKeyword,
            Token::BeepKeyword => SyntaxKind::BeepKeyword,
            Token::AppActivateKeyword => SyntaxKind::AppActivateKeyword,
            Token::FriendKeyword => SyntaxKind::FriendKeyword,
            Token::BinaryKeyword => SyntaxKind::BinaryKeyword,
            Token::RandomKeyword => SyntaxKind::RandomKeyword,
            Token::ReadKeyword => SyntaxKind::ReadKeyword,
            Token::OutputKeyword => SyntaxKind::OutputKeyword,
            Token::AppendKeyword => SyntaxKind::AppendKeyword,
            Token::AccessKeyword => SyntaxKind::AccessKeyword,
            Token::TextKeyword => SyntaxKind::TextKeyword,
            Token::DatabaseKeyword => SyntaxKind::DatabaseKeyword,
            Token::EmptyKeyword => SyntaxKind::EmptyKeyword,
            Token::ModuleKeyword => SyntaxKind::ModuleKeyword,
            Token::NextKeyword => SyntaxKind::NextKeyword,
            Token::NewKeyword => SyntaxKind::NewKeyword,
            Token::LenKeyword => SyntaxKind::LenKeyword,
            Token::MeKeyword => SyntaxKind::MeKeyword,
            Token::NullKeyword => SyntaxKind::NullKeyword,
            Token::ParamArrayKeyword => SyntaxKind::ParamArrayKeyword,
            Token::DollarSign => SyntaxKind::DollarSign,
            Token::Underscore => SyntaxKind::Underscore,
            Token::Ampersand => SyntaxKind::Ampersand,
            Token::Percent => SyntaxKind::Percent,
            Token::Octothorpe => SyntaxKind::Octothorpe,
            Token::LeftParenthesis => SyntaxKind::LeftParenthesis,
            Token::RightParenthesis => SyntaxKind::RightParenthesis,
            Token::LeftSquareBracket => SyntaxKind::LeftSquareBracket,
            Token::RightSquareBracket => SyntaxKind::RightSquareBracket,
            Token::Comma => SyntaxKind::Comma,
            Token::Semicolon => SyntaxKind::Semicolon,
            Token::AtSign => SyntaxKind::AtSign,
            Token::ExclamationMark => SyntaxKind::ExclamationMark,
            Token::VersionKeyword => SyntaxKind::VersionKeyword,
            Token::EqualityOperator => SyntaxKind::EqualityOperator,
            Token::InequalityOperator => SyntaxKind::InequalityOperator,
            Token::LessThanOrEqualOperator => SyntaxKind::LessThanOrEqualOperator,
            Token::GreaterThanOrEqualOperator => SyntaxKind::GreaterThanOrEqualOperator,
            Token::LessThanOperator => SyntaxKind::LessThanOperator,
            Token::GreaterThanOperator => SyntaxKind::GreaterThanOperator,
            Token::MultiplicationOperator => SyntaxKind::MultiplicationOperator,
            Token::SubtractionOperator => SyntaxKind::SubtractionOperator,
            Token::AdditionOperator => SyntaxKind::AdditionOperator,
            Token::DivisionOperator => SyntaxKind::DivisionOperator,
            Token::BackwardSlashOperator => SyntaxKind::BackwardSlashOperator,
            Token::PeriodOperator => SyntaxKind::PeriodOperator,
            Token::ColonOperator => SyntaxKind::ColonOperator,
            Token::ExponentiationOperator => SyntaxKind::ExponentiationOperator,
            Token::Identifier => SyntaxKind::Identifier,
        }
    }
}

impl SyntaxKind {
    pub(crate) fn from_raw(raw: rowan::SyntaxKind) -> Self {
        assert!(raw.0 <= SyntaxKind::Unknown as u16);
        unsafe { std::mem::transmute::<u16, SyntaxKind>(raw.0) }
    }

    /// Convert `SyntaxKind` to rowan's raw `SyntaxKind` (for internal use in builders)
    pub(crate) fn to_raw(self) -> rowan::SyntaxKind {
        rowan::SyntaxKind(self as u16)
    }
}
