use crate::language::VB6Token;

/// Syntax kinds for the VB6 CST.
///
/// This enum represents all possible node and token types in the CST.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u16)]
pub enum SyntaxKind {
    // Root node
    Root = 0,

    // Statement nodes
    ModuleStatement,
    ClassStatement,
    SubStatement,
    FunctionStatement,
    PropertyStatement,
    DimStatement,
    ConstStatement,
    TypeStatement,
    EnumStatement,
    IfStatement,
    ElseIfClause,
    ElseClause,
    ForStatement,
    ForEachStatement,
    WhileStatement,
    DoStatement,
    SelectCaseStatement,
    CaseClause,
    CaseElseClause,
    WithStatement,
    CallStatement,
    SetStatement,
    AssignmentStatement,
    GotoStatement,
    ExitStatement,
    AppActivateStatement,
    BeepStatement,
    ChDirStatement,
    LabelStatement,
    AttributeStatement,
    OptionStatement,

    // Expression nodes
    BinaryExpression,
    UnaryExpression,
    LiteralExpression,
    IdentifierExpression,
    MemberAccessExpression,
    CallExpression,
    ParenthesizedExpression,

    // Conditional nodes
    BinaryConditional,
    UnaryConditional,

    // Other structural nodes
    ArgumentList,
    ParameterList,
    Parameter,
    Argument,
    CodeBlock,

    // Token kinds - map from VB6Token
    // We start these at a higher offset to avoid conflicts
    Whitespace = 1000,
    Newline,
    EndOfLineComment,
    RemComment,

    // Keywords
    ClassKeyword,
    ReDimKeyword,
    PreserveKeyword,
    DimKeyword,
    DeclareKeyword,
    AliasKeyword,
    AttributeKeyword,
    BeginKeyword,
    LibKeyword,
    WithKeyword,
    WithEventsKeyword,
    BaseKeyword,
    CompareKeyword,
    OptionKeyword,
    ExplicitKeyword,
    PrivateKeyword,
    PublicKeyword,
    ConstKeyword,
    AsKeyword,
    ByValKeyword,
    ByRefKeyword,
    OptionalKeyword,
    FunctionKeyword,
    StaticKeyword,
    SubKeyword,
    EndKeyword,
    TrueKeyword,
    FalseKeyword,
    EnumKeyword,
    TypeKeyword,
    BooleanKeyword,
    DoubleKeyword,
    CurrencyKeyword,
    DecimalKeyword,
    DateKeyword,
    ObjectKeyword,
    VariantKeyword,
    ByteKeyword,
    LongKeyword,
    SingleKeyword,
    StringKeyword,
    IntegerKeyword,
    IfKeyword,
    ElseKeyword,
    ElseIfKeyword,
    AndKeyword,
    OrKeyword,
    XorKeyword,
    ModKeyword,
    EqvKeyword,
    AddressOfKeyword,
    ImpKeyword,
    IsKeyword,
    LikeKeyword,
    NotKeyword,
    ThenKeyword,
    GotoKeyword,
    ExitKeyword,
    ForKeyword,
    EachKeyword,
    InKeyword,
    ToKeyword,
    LockKeyword,
    UnlockKeyword,
    StepKeyword,
    StopKeyword,
    WhileKeyword,
    WendKeyword,
    WidthKeyword,
    WriteKeyword,
    TimeKeyword,
    SetAttrKeyword,
    SetKeyword,
    SendKeysKeyword,
    SelectKeyword,
    CaseKeyword,
    SeekKeyword,
    SaveSettingKeyword,
    SavePictureKeyword,
    RSetKeyword,
    RmDirKeyword,
    ResumeKeyword,
    ResetKeyword,
    RandomizeKeyword,
    RaiseEventKeyword,
    PutKeyword,
    PropertyKeyword,
    PrintKeyword,
    OpenKeyword,
    OnKeyword,
    OffKeyword,
    NameKeyword,
    MkDirKeyword,
    MidKeyword,
    LSetKeyword,
    LoadKeyword,
    LineKeyword,
    InputKeyword,
    LetKeyword,
    KillKeyword,
    ImplementsKeyword,
    GetKeyword,
    FileCopyKeyword,
    EventKeyword,
    ErrorKeyword,
    EraseKeyword,
    DoKeyword,
    UntilKeyword,
    DeleteSettingKeyword,
    DefBoolKeyword,
    DefByteKeyword,
    DefIntKeyword,
    DefLngKeyword,
    DefCurKeyword,
    DefSngKeyword,
    DefDblKeyword,
    DefDecKeyword,
    DefDateKeyword,
    DefStrKeyword,
    DefObjKeyword,
    DefVarKeyword,
    CloseKeyword,
    ChDriveKeyword,
    ChDirKeyword,
    CallKeyword,
    BeepKeyword,
    AppActivateKeyword,
    FriendKeyword,
    BinaryKeyword,
    EmptyKeyword,
    NextKeyword,
    NewKeyword,
    LenKeyword,
    MeKeyword,
    NullKeyword,
    ParamArrayKeyword,
    VersionKeyword,
    LoopKeyword,
    NothingKeyword,
    AnyKeyword,

    // Literals and identifiers
    Identifier,
    StringLiteral,
    Number,

    // Operators and punctuation
    DollarSign,
    Underscore,
    Ampersand,
    Percent,
    Octothorpe,
    LeftParentheses,
    RightParentheses,
    LeftSquareBracket,
    RightSquareBracket,
    Comma,
    Semicolon,
    AtSign,
    ExclamationMark,
    EqualityOperator,
    LessThanOperator,
    GreaterThanOperator,
    MultiplicationOperator,
    SubtractionOperator,
    AdditionOperator,
    DivisionOperator,
    BackwardSlashOperator,
    PeriodOperator,
    ColonOperator,
    ExponentiationOperator,

    // Error recovery
    Error,
    Unknown,
}

impl From<VB6Token> for SyntaxKind {
    fn from(token: VB6Token) -> Self {
        match token {
            VB6Token::Whitespace => SyntaxKind::Whitespace,
            VB6Token::Newline => SyntaxKind::Newline,
            VB6Token::EndOfLineComment => SyntaxKind::EndOfLineComment,
            VB6Token::RemComment => SyntaxKind::RemComment,
            VB6Token::ClassKeyword => SyntaxKind::ClassKeyword,
            VB6Token::ReDimKeyword => SyntaxKind::ReDimKeyword,
            VB6Token::PreserveKeyword => SyntaxKind::PreserveKeyword,
            VB6Token::DimKeyword => SyntaxKind::DimKeyword,
            VB6Token::DeclareKeyword => SyntaxKind::DeclareKeyword,
            VB6Token::AliasKeyword => SyntaxKind::AliasKeyword,
            VB6Token::AttributeKeyword => SyntaxKind::AttributeKeyword,
            VB6Token::BeginKeyword => SyntaxKind::BeginKeyword,
            VB6Token::LibKeyword => SyntaxKind::LibKeyword,
            VB6Token::WithKeyword => SyntaxKind::WithKeyword,
            VB6Token::WithEventsKeyword => SyntaxKind::WithEventsKeyword,
            VB6Token::BaseKeyword => SyntaxKind::BaseKeyword,
            VB6Token::CompareKeyword => SyntaxKind::CompareKeyword,
            VB6Token::OptionKeyword => SyntaxKind::OptionKeyword,
            VB6Token::ExplicitKeyword => SyntaxKind::ExplicitKeyword,
            VB6Token::PrivateKeyword => SyntaxKind::PrivateKeyword,
            VB6Token::PublicKeyword => SyntaxKind::PublicKeyword,
            VB6Token::ConstKeyword => SyntaxKind::ConstKeyword,
            VB6Token::AsKeyword => SyntaxKind::AsKeyword,
            VB6Token::ByValKeyword => SyntaxKind::ByValKeyword,
            VB6Token::ByRefKeyword => SyntaxKind::ByRefKeyword,
            VB6Token::OptionalKeyword => SyntaxKind::OptionalKeyword,
            VB6Token::FunctionKeyword => SyntaxKind::FunctionKeyword,
            VB6Token::StaticKeyword => SyntaxKind::StaticKeyword,
            VB6Token::SubKeyword => SyntaxKind::SubKeyword,
            VB6Token::EndKeyword => SyntaxKind::EndKeyword,
            VB6Token::TrueKeyword => SyntaxKind::TrueKeyword,
            VB6Token::FalseKeyword => SyntaxKind::FalseKeyword,
            VB6Token::EnumKeyword => SyntaxKind::EnumKeyword,
            VB6Token::TypeKeyword => SyntaxKind::TypeKeyword,
            VB6Token::BooleanKeyword => SyntaxKind::BooleanKeyword,
            VB6Token::DoubleKeyword => SyntaxKind::DoubleKeyword,
            VB6Token::CurrencyKeyword => SyntaxKind::CurrencyKeyword,
            VB6Token::DecimalKeyword => SyntaxKind::DecimalKeyword,
            VB6Token::DateKeyword => SyntaxKind::DateKeyword,
            VB6Token::ObjectKeyword => SyntaxKind::ObjectKeyword,
            VB6Token::VariantKeyword => SyntaxKind::VariantKeyword,
            VB6Token::ByteKeyword => SyntaxKind::ByteKeyword,
            VB6Token::LongKeyword => SyntaxKind::LongKeyword,
            VB6Token::SingleKeyword => SyntaxKind::SingleKeyword,
            VB6Token::StringKeyword => SyntaxKind::StringKeyword,
            VB6Token::IntegerKeyword => SyntaxKind::IntegerKeyword,
            VB6Token::StringLiteral => SyntaxKind::StringLiteral,
            VB6Token::IfKeyword => SyntaxKind::IfKeyword,
            VB6Token::ElseKeyword => SyntaxKind::ElseKeyword,
            VB6Token::ElseIfKeyword => SyntaxKind::ElseIfKeyword,
            VB6Token::AndKeyword => SyntaxKind::AndKeyword,
            VB6Token::OrKeyword => SyntaxKind::OrKeyword,
            VB6Token::XorKeyword => SyntaxKind::XorKeyword,
            VB6Token::ModKeyword => SyntaxKind::ModKeyword,
            VB6Token::EqvKeyword => SyntaxKind::EqvKeyword,
            VB6Token::AddressOfKeyword => SyntaxKind::AddressOfKeyword,
            VB6Token::ImpKeyword => SyntaxKind::ImpKeyword,
            VB6Token::IsKeyword => SyntaxKind::IsKeyword,
            VB6Token::LikeKeyword => SyntaxKind::LikeKeyword,
            VB6Token::NotKeyword => SyntaxKind::NotKeyword,
            VB6Token::ThenKeyword => SyntaxKind::ThenKeyword,
            VB6Token::GotoKeyword => SyntaxKind::GotoKeyword,
            VB6Token::ExitKeyword => SyntaxKind::ExitKeyword,
            VB6Token::ForKeyword => SyntaxKind::ForKeyword,
            VB6Token::EachKeyword => SyntaxKind::EachKeyword,
            VB6Token::InKeyword => SyntaxKind::InKeyword,
            VB6Token::ToKeyword => SyntaxKind::ToKeyword,
            VB6Token::LockKeyword => SyntaxKind::LockKeyword,
            VB6Token::UnlockKeyword => SyntaxKind::UnlockKeyword,
            VB6Token::StepKeyword => SyntaxKind::StepKeyword,
            VB6Token::StopKeyword => SyntaxKind::StopKeyword,
            VB6Token::WhileKeyword => SyntaxKind::WhileKeyword,
            VB6Token::WendKeyword => SyntaxKind::WendKeyword,
            VB6Token::WidthKeyword => SyntaxKind::WidthKeyword,
            VB6Token::WriteKeyword => SyntaxKind::WriteKeyword,
            VB6Token::TimeKeyword => SyntaxKind::TimeKeyword,
            VB6Token::SetAttrKeyword => SyntaxKind::SetAttrKeyword,
            VB6Token::SetKeyword => SyntaxKind::SetKeyword,
            VB6Token::SendKeysKeyword => SyntaxKind::SendKeysKeyword,
            VB6Token::SelectKeyword => SyntaxKind::SelectKeyword,
            VB6Token::CaseKeyword => SyntaxKind::CaseKeyword,
            VB6Token::SeekKeyword => SyntaxKind::SeekKeyword,
            VB6Token::SaveSettingKeyword => SyntaxKind::SaveSettingKeyword,
            VB6Token::SavePictureKeyword => SyntaxKind::SavePictureKeyword,
            VB6Token::RSetKeyword => SyntaxKind::RSetKeyword,
            VB6Token::RmDirKeyword => SyntaxKind::RmDirKeyword,
            VB6Token::ResumeKeyword => SyntaxKind::ResumeKeyword,
            VB6Token::ResetKeyword => SyntaxKind::ResetKeyword,
            VB6Token::RandomizeKeyword => SyntaxKind::RandomizeKeyword,
            VB6Token::RaiseEventKeyword => SyntaxKind::RaiseEventKeyword,
            VB6Token::PutKeyword => SyntaxKind::PutKeyword,
            VB6Token::PropertyKeyword => SyntaxKind::PropertyKeyword,
            VB6Token::PrintKeyword => SyntaxKind::PrintKeyword,
            VB6Token::OpenKeyword => SyntaxKind::OpenKeyword,
            VB6Token::OnKeyword => SyntaxKind::OnKeyword,
            VB6Token::OffKeyword => SyntaxKind::OffKeyword,
            VB6Token::NameKeyword => SyntaxKind::NameKeyword,
            VB6Token::MkDirKeyword => SyntaxKind::MkDirKeyword,
            VB6Token::MidKeyword => SyntaxKind::MidKeyword,
            VB6Token::LSetKeyword => SyntaxKind::LSetKeyword,
            VB6Token::LoadKeyword => SyntaxKind::LoadKeyword,
            VB6Token::LineKeyword => SyntaxKind::LineKeyword,
            VB6Token::InputKeyword => SyntaxKind::InputKeyword,
            VB6Token::LetKeyword => SyntaxKind::LetKeyword,
            VB6Token::KillKeyword => SyntaxKind::KillKeyword,
            VB6Token::ImplementsKeyword => SyntaxKind::ImplementsKeyword,
            VB6Token::GetKeyword => SyntaxKind::GetKeyword,
            VB6Token::FileCopyKeyword => SyntaxKind::FileCopyKeyword,
            VB6Token::EventKeyword => SyntaxKind::EventKeyword,
            VB6Token::ErrorKeyword => SyntaxKind::ErrorKeyword,
            VB6Token::EraseKeyword => SyntaxKind::EraseKeyword,
            VB6Token::DoKeyword => SyntaxKind::DoKeyword,
            VB6Token::UntilKeyword => SyntaxKind::UntilKeyword,
            VB6Token::LoopKeyword => SyntaxKind::LoopKeyword,
            VB6Token::DeleteSettingKeyword => SyntaxKind::DeleteSettingKeyword,
            VB6Token::DefBoolKeyword => SyntaxKind::DefBoolKeyword,
            VB6Token::DefByteKeyword => SyntaxKind::DefByteKeyword,
            VB6Token::DefIntKeyword => SyntaxKind::DefIntKeyword,
            VB6Token::DefLngKeyword => SyntaxKind::DefLngKeyword,
            VB6Token::DefCurKeyword => SyntaxKind::DefCurKeyword,
            VB6Token::DefSngKeyword => SyntaxKind::DefSngKeyword,
            VB6Token::DefDblKeyword => SyntaxKind::DefDblKeyword,
            VB6Token::DefDecKeyword => SyntaxKind::DefDecKeyword,
            VB6Token::DefDateKeyword => SyntaxKind::DefDateKeyword,
            VB6Token::DefStrKeyword => SyntaxKind::DefStrKeyword,
            VB6Token::DefObjKeyword => SyntaxKind::DefObjKeyword,
            VB6Token::DefVarKeyword => SyntaxKind::DefVarKeyword,
            VB6Token::CloseKeyword => SyntaxKind::CloseKeyword,
            VB6Token::ChDriveKeyword => SyntaxKind::ChDriveKeyword,
            VB6Token::ChDirKeyword => SyntaxKind::ChDirKeyword,
            VB6Token::CallKeyword => SyntaxKind::CallKeyword,
            VB6Token::BeepKeyword => SyntaxKind::BeepKeyword,
            VB6Token::AppActivateKeyword => SyntaxKind::AppActivateKeyword,
            VB6Token::FriendKeyword => SyntaxKind::FriendKeyword,
            VB6Token::BinaryKeyword => SyntaxKind::BinaryKeyword,
            VB6Token::EmptyKeyword => SyntaxKind::EmptyKeyword,
            VB6Token::NextKeyword => SyntaxKind::NextKeyword,
            VB6Token::NewKeyword => SyntaxKind::NewKeyword,
            VB6Token::LenKeyword => SyntaxKind::LenKeyword,
            VB6Token::MeKeyword => SyntaxKind::MeKeyword,
            VB6Token::NullKeyword => SyntaxKind::NullKeyword,
            VB6Token::ParamArrayKeyword => SyntaxKind::ParamArrayKeyword,
            VB6Token::DollarSign => SyntaxKind::DollarSign,
            VB6Token::Underscore => SyntaxKind::Underscore,
            VB6Token::Ampersand => SyntaxKind::Ampersand,
            VB6Token::Percent => SyntaxKind::Percent,
            VB6Token::Octothorpe => SyntaxKind::Octothorpe,
            VB6Token::LeftParentheses => SyntaxKind::LeftParentheses,
            VB6Token::RightParentheses => SyntaxKind::RightParentheses,
            VB6Token::LeftSquareBracket => SyntaxKind::LeftSquareBracket,
            VB6Token::RightSquareBracket => SyntaxKind::RightSquareBracket,
            VB6Token::Comma => SyntaxKind::Comma,
            VB6Token::Semicolon => SyntaxKind::Semicolon,
            VB6Token::AtSign => SyntaxKind::AtSign,
            VB6Token::ExclamationMark => SyntaxKind::ExclamationMark,
            VB6Token::VersionKeyword => SyntaxKind::VersionKeyword,
            VB6Token::EqualityOperator => SyntaxKind::EqualityOperator,
            VB6Token::LessThanOperator => SyntaxKind::LessThanOperator,
            VB6Token::GreaterThanOperator => SyntaxKind::GreaterThanOperator,
            VB6Token::MultiplicationOperator => SyntaxKind::MultiplicationOperator,
            VB6Token::SubtractionOperator => SyntaxKind::SubtractionOperator,
            VB6Token::AdditionOperator => SyntaxKind::AdditionOperator,
            VB6Token::DivisionOperator => SyntaxKind::DivisionOperator,
            VB6Token::BackwardSlashOperator => SyntaxKind::BackwardSlashOperator,
            VB6Token::PeriodOperator => SyntaxKind::PeriodOperator,
            VB6Token::ColonOperator => SyntaxKind::ColonOperator,
            VB6Token::ExponentiationOperator => SyntaxKind::ExponentiationOperator,
            VB6Token::Identifier => SyntaxKind::Identifier,
            VB6Token::Number => SyntaxKind::Number,
        }
    }
}

impl SyntaxKind {
    pub(crate) fn from_raw(raw: rowan::SyntaxKind) -> Self {
        assert!(raw.0 <= SyntaxKind::Unknown as u16);
        unsafe { std::mem::transmute::<u16, SyntaxKind>(raw.0) }
    }

    /// Convert SyntaxKind to rowan's raw SyntaxKind (for internal use in builders)
    pub(crate) fn to_raw(self) -> rowan::SyntaxKind {
        rowan::SyntaxKind(self as u16)
    }
}
